version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./test_audio:/app/test_audio  # For testing with local audio files
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload