version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount source files for hot reload
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./requirements.txt:/app/requirements.txt
      # Exclude certain directories to improve performance
      - /app/creapy
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true  # Better file watching in containers
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app --reload-exclude /app/creapy
    develop:
      watch:
        - action: sync
          path: ./app.py
          target: /app/app.py
        - action: sync
          path: ./static
          target: /app/static