services:
  - type: web
    name: creaky-voice-detector
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: false